name: 'Gallery vue'
description: 'make gallery page with vuejs'
author: 'botamochi6277'
branding:
  icon: 'image'
  color: 'green'
inputs:
  dir:
    description: 'target directory containing images'
    default: 'imgs'
    required: true
  outpath:
    description: 'target directory to saving image list'
    default: '.'
    required: true
runs:
  steps:
    - name: docker
      using: 'docker'
      image: 'Dockerfile'
      args:
        - ${{ inputs.dir }} ${{ inputs.outpath }}
