name: Build Vue and Deploy on Pages
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - id: Build-Vue
        uses: botamochi6277/gallery-action-vue:main
        with:
          dir: 'imgs'
          outpath: '.'
      - name: git setting
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
        run: |
          git config --local user.email "action_runner@users.noreply.github.com"
          git config --local user.name "action runner"
      - name: Commit and push files
        run: |
          git checkout -b gh-pages
          git add .
          git commit -m "build pages" -a
          git pull
          git push origin gh-pages -u
